root: true

env:
  browser: true
  es2020: true

parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: .
  project:
    - ./tsconfig.eslint.json
    - ./tsconfig.json
    - ./packages/*/tsconfig.json

plugins:
  - '@typescript-eslint'
  - prettier
  - react-hooks
  - react-refresh
  - import

rules:
  prettier/prettier: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  react-refresh/only-export-components:
    - error
    - allowConstantExport: true

  import/order: error

  '@typescript-eslint/dot-notation': error
  '@typescript-eslint/prefer-readonly': error
  # '@typescript-eslint/prefer-readonly-parameter-types': error
  '@typescript-eslint/array-type':
    - error
    - default: array-simple

  '@typescript-eslint/no-inferrable-types': error
  '@typescript-eslint/prefer-as-const': error
  '@typescript-eslint/non-nullable-type-assertion-style': error
  # '@typescript-eslint/no-unsafe-return': error
  '@typescript-eslint/no-unsafe-enum-comparison': error
  '@typescript-eslint/prefer-includes': error
  '@typescript-eslint/switch-exhaustiveness-check': error
  '@typescript-eslint/sort-type-constituents': error
  # '@typescript-eslint/strict-boolean-expressions': error
  '@typescript-eslint/prefer-ts-expect-error': error
  '@typescript-eslint/prefer-string-starts-ends-with': error
  # '@typescript-eslint/prefer-nullish-coalescing': error
  # '@typescript-eslint/unbound-method': error
