[package]
name = "service"
version = "2.3.1"
description = "REST and GraphQL server for validating data received via the Telegram Mini App"
publish = false
license = "MIT"
license-file = "LICENSE.md"
repository = "https://github.com/bigslycat/tg-app"
authors = ["Pavel Tereschenko <me@stupidcat.wtf>"]
edition = "2021"

[dependencies]
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
urlencoding = "2.1.3"
serde_json = "1.0.108"
async-graphql-rocket = "6.0.11"
async-graphql = "6.0.11"
serde = { version = "1.0.193", features = ["derive"] }
rocket = { version = "0.5.0", features = ["json"] }
utoipa = { version = "4.2.0", features = ["rocket_extras"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["rocket"] }
utoipa-redoc = { version = "3.0.0", features = ["rocket"] }
utoipa-rapidoc = { version = "3.0.0", features = ["rocket"] }
rocket_cors = "0.6.0"

[build-dependencies]
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
urlencoding = "2.1.3"
serde_json = "1.0.108"
async-graphql-rocket = "6.0.11"
async-graphql = "6.0.11"
serde = { version = "1.0.193", features = ["derive"] }
rocket = { version = "0.5.0", features = ["json"] }
regex = "1.10.2"
utoipa = { version = "4.2.0", features = ["rocket_extras"] }
