[package]
name = "service"
version = "1.0.0"
description = "REST and GraphQL server for validating data received via the Telegram Mini App"
publish = false
license = "MIT"
license-file = "LICENSE.md"
repository = "https://github.com/bigslycat/tg-app-validate-service"
authors = ["Pavel Tereschenko <me@stupidcat.wtf>"]
edition = "2021"

[dependencies]
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
urlencoding = "2.1.3"
serde_json = "1.0.108"
async-graphql-rocket = "6.0.11"
async-graphql = "6.0.11"
serde = { version = "1.0.193", features = ["derive"] }
rocket = { version = "0.5.0", features = ["json"] }

[build-dependencies]
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
urlencoding = "2.1.3"
serde_json = "1.0.108"
async-graphql-rocket = "6.0.11"
async-graphql = "6.0.11"
serde = { version = "1.0.193", features = ["derive"] }
rocket = { version = "0.5.0", features = ["json"] }
regex = "1.10.2"
