name: Publish @tg-app/validation-service-gql-schema package

on:
  push:
    tags:
      - 'schema/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          scope: '@tg-app'
      - run: yarn rebuild
      - run: yarn workspace @tg-app/validation-service-gql-schema build
      - run: yarn workspace @tg-app/validation-service-gql-schema npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
